# Generated by Django 2.2.10 on 2020-05-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=100, verbose_name='Produto')),
                ('produto_quantidade', models.IntegerField()),
                ('produto_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Fornecedor', verbose_name='Fornecedor')),
            ],
        ),
    ]
