# Generated by Django 2.2.10 on 2020-05-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produto_descricao',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='produto_imagem',
            field=models.ImageField(null=True, upload_to='produtos/%Y/%m'),
        ),
    ]
