# Generated by Django 2.2.10 on 2020-05-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20200516_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produto_preco',
            field=models.FloatField(null=True),
        ),
    ]
