# Generated by Django 2.2.10 on 2020-05-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixa',
            name='baixa_motivo',
            field=models.TextField(null=True),
        ),
    ]
