# Generated by Django 2.2.10 on 2020-05-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baixa', '0002_baixa_baixa_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixa',
            name='baixa_motivo',
            field=models.TextField(),
        ),
    ]
