# Generated by Django 2.2.10 on 2020-05-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baixa', '0003_auto_20200514_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixa',
            name='baixa_data',
            field=models.DateField(auto_now=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='baixa',
            name='baixa_motivo',
            field=models.TextField(verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='baixa',
            name='baixa_quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
    ]
