# Generated by Django 2.2.10 on 2020-05-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baixa', '0005_auto_20200514_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixa',
            name='baixa_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto', verbose_name='Baixa'),
        ),
    ]
