# Generated by Django 2.2.10 on 2020-05-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baixa', '0007_baixa_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixa',
            name='baixa_data',
            field=models.DateTimeField(auto_now=True, verbose_name='Data'),
        ),
    ]
