# Generated by Django 2.2.10 on 2020-05-16 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baixa', '0008_auto_20200515_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixa',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
