# Generated by Django 2.2.10 on 2020-05-16 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_data', models.DateTimeField(auto_now=True)),
                ('entrada_quantidade', models.IntegerField()),
                ('entrada_motivo', models.TextField()),
                ('entrada_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.Produto', verbose_name='Produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
