# Generated by Django 2.2.10 on 2020-05-16 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_auto_20200516_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='entrada_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto', verbose_name='Produto'),
        ),
    ]
